name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
          
  dockerhub:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Install Docker
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/accountpage:latest ./AccountPage
    - name: Push Image To DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/accountpage:latest
